"""Topic tags for memegen's templates, keyed by template id.

memegen files most templates under the quote ("Butthurt Dweller", "Y'all
Got Any More of Them") and only a quarter of them carry keywords, so a
search for a topic — gym, monday, argument — comes back empty even when
a template fits. This table is the missing keyword column: each id gets
the characters and franchises people name it by plus the situations it
is used for. The catalog folds these in as keywords, so ``@meme list gym``
finds them and ``@meme gym | ... `` resolves through the same tiers as
any other keyword — a tag shared by two templates is an ambiguity, not a
guess.

Hand-written from memegen's names and example captions on 2026-09-18. An
id memegen no longer serves is ignored; a new template it adds simply
has no tags until someone writes them. Keep tags lowercase; the resolver
normalises them anyway.

These tags also feed the picker (``prompts.MEME_PICK_PROMPT``): when a
request names no template, a model reads this table beside the names and
example captions and chooses one, and :func:`meme.parse_pick` checks the
answer against the catalog before memegen sees it.
"""

from __future__ import annotations

TOPICS: dict[str, tuple[str, ...]] = {
    "3hd": ("godzilla", "three heads", "three options", "pizza"),
    "aag": ("aliens", "conspiracy", "history channel", "giorgio"),
    "ackbar": ("star wars", "trap", "ambush", "suspicious"),
    "afraid": ("too afraid to ask", "confused", "ignorance", "andy dwyer"),
    "agnes": ("wink", "terms and conditions", "lying", "agree"),
    "aint-got-time": ("no time", "busy", "sweet brown", "ain't nobody"),
    "ams": ("awkward", "embarrassed", "seal", "parents"),
    "ants": ("archer", "consequences", "how you get"),
    "apcr": ("redneck", "backhanded", "politically incorrect"),
    "astronaut": ("always has been", "space", "gun", "betrayal", "reveal", "twist"),
    "atis": ("and then i said", "laughing", "lie", "promise"),
    "away": ("jurassic park", "jeff goldblum", "ian malcolm", "life finds a way"),
    "awesome": ("penguin", "socially awesome", "lucky", "win"),
    "awesome-awkward": ("penguin", "good then bad", "fail"),
    "awkward": ("penguin", "socially awkward", "shy", "cringe"),
    "awkward-awesome": ("penguin", "bad then good", "accidental win"),
    "bad": ("zoidberg", "futurama", "feel bad", "shame", "criticism"),
    "badchoice": ("ron burgundy", "anchorman", "will ferrell", "regret", "mistake"),
    "balloon": ("held back", "missed opportunity", "shyness", "anxiety"),
    "bd": ("lazy", "excuse", "basement", "neckbeard", "can't workout", "fat", "smug"),
    "because": ("will smith", "mib", "racism", "just because"),
    "bender": ("futurama", "blackjack and hookers", "my own", "fork", "start over"),
    "bihw": ("honest work", "farmer", "modest", "humble", "job"),
    "bilbo": ("lord of the rings", "hobbit", "keep it", "greed", "possessive", "ring"),
    "biw": ("baby", "wolf", "mild", "rebel", "living dangerously"),
    "blb": ("bad luck", "unlucky", "brian", "misfortune"),
    "boat": ("cat", "buy a boat", "spending", "impulse"),
    "bongo": ("cat", "loud", "noise", "sleep", "alarm"),
    "both": ("why not both", "girl", "tacos", "choice", "compromise"),
    "box": ("seven", "brad pitt", "whats in the box", "screaming"),
    "bs": ("bull shark", "caught", "surprise", "sarcasm"),
    "bus": ("two guys", "bus", "happy sad", "sun shade", "contrast", "before after"),
    "buzz": ("toy story", "woody", "everywhere", "buzz lightyear"),
    "cake": ("office space", "milton", "stapler", "promised", "let down"),
    "captain": ("captain phillips", "somali", "i am the captain", "takeover", "control"),
    "captain-america": ("elevator", "dad joke", "pun", "marvel", "fight"),
    "cb": ("bear", "confession", "guilty", "secret", "admit"),
    "cbb": ("bugs bunny", "communist", "our", "sharing", "ours"),
    "cbg": ("simpsons", "comic book guy", "worst ever", "nerd", "critic"),
    "center": ("zoolander", "ben stiller", "too small", "tiny", "ants"),
    "ch": ("south park", "hindsight", "obvious", "should have"),
    "chair": ("american chopper", "argument", "yelling", "debate", "escalating", "six panel"),
    "cheems": ("doge", "dog", "shiba", "weak", "calm", "nothing will go wrong"),
    "chosen": ("star wars", "obi-wan", "anakin", "chosen one", "betrayal", "disappointed"),
    "cmm": ("steven crowder", "debate", "opinion", "hot take", "sign", "table"),
    "country": ("simpsons", "dr nick", "america", "immigrant"),
    "crazypills": ("zoolander", "mugatu", "crazy", "am i the only one", "frustrated"),
    "crow": ("crow", "material", "joke", "repeat", "stale", "comedian"),
    "crowd": ("celebration", "football", "soccer", "bar", "cheering", "hype", "ci"),
    "cryingfloor": ("crying", "drinking", "hangover", "sad", "floor"),
    "db": ("cheating", "temptation", "distracted", "new shiny", "girlfriend", "boyfriend"),
    "dbg": ("disappointed", "expectation", "reality", "letdown", "black guy"),
    "dg": ("distracted", "girlfriend", "temptation", "gender swap"),
    "disastergirl": ("fire", "evil smile", "arson", "planned", "chaos"),
    "dodgson": ("jurassic park", "nobody cares", "ignored", "dennis nedry"),
    "doge": ("dog", "shiba", "wow", "such", "very"),
    "dragon": ("wish", "dragon", "misheard", "genie", "boyfriend"),
    "drake": ("drake", "hotline bling", "prefer", "no yes", "approve disapprove", "choice"),
    "drowning": ("drowning", "high five", "ignored", "help", "misunderstood", "forum"),
    "drunk": ("baby", "drunk", "alcohol", "hangover"),
    "ds": ("daily struggle", "two buttons", "sweating", "dilemma", "choice", "decision"),
    "dsm": ("dating", "creepy", "murderer", "compliment"),
    "dwight": ("the office", "dwight schrute", "false", "fact", "correction"),
    "elf": ("elf", "will ferrell", "liar", "lies", "throne of lies"),
    "elmo": ("elmo", "cocaine", "choice", "temptation", "sesame street"),
    "ermg": ("ermahgerd", "excited", "goosebumps", "girl", "books"),
    "exit": ("exit", "off ramp", "car", "swerve", "choice", "highway"),
    "fa": ("forever alone", "lonely", "single", "rage comic"),
    "facepalm": ("facepalm", "picard", "star trek", "can't even", "disbelief"),
    "fbf": ("frog", "bachelor", "lazy", "gross", "single"),
    "fetch": ("mean girls", "regina george", "not going to happen", "give up"),
    "feelsgood": ("feels good", "satisfied", "rage comic", "relief"),
    "fine": ("dog", "fire", "everything is fine", "denial", "coping", "burning", "chaos"),
    "firsttry": ("first try", "lucky", "nailed it", "rage comic"),
    "fmr": ("dean winchester", "supernatural", "fuck me", "unlucky", "screwed"),
    "friends": ("star trek", "picard", "riker", "rivals", "enemies", "political"),
    "fry": ("futurama", "not sure if", "squint", "suspicious", "unsure"),
    "fwp": ("first world problems", "crying", "privilege", "minor complaint"),
    "gandalf": ("lord of the rings", "confused", "forgot", "no memory", "lost"),
    "gb": ("expanding brain", "galaxy brain", "big brain", "escalation", "enlightened"),
    "gears": ("family guy", "peter griffin", "grinds my gears", "annoyed", "pet peeve"),
    "genie": ("aladdin", "genie", "power", "cramped", "small space"),
    "ggg": ("good guy", "nice", "helpful", "wholesome"),
    "glasses": ("spider-man", "peter parker", "glasses", "clarity", "cope", "reveal"),
    "gone": ("south park", "bank", "money", "gone", "investment", "lost"),
    "grave": ("grave", "arrow", "flash", "dead", "rip", "society"),
    "gru": ("despicable me", "plan", "backfire", "realisation", "four panel", "oops"),
    "grumpycat": ("cat", "grumpy", "no", "hate", "misery"),
    "hagrid": ("harry potter", "said too much", "oops", "secret", "slip"),
    "handshake": ("handshake", "agreement", "common ground", "unite", "predator", "alliance"),
    "happening": ("ron paul", "it's happening", "excited", "hype", "finally"),
    "harold": ("harold", "hide the pain", "forced smile", "suffering", "old man", "boss"),
    "headaches": ("headache", "migraine", "pain", "stress", "types of"),
    "hipster": ("hipster", "barista", "coffee", "pretentious"),
    "home": ("mom", "food at home", "cheap", "disappointing", "parents"),
    "icanhas": ("cat", "cheezburger", "lolcat", "please"),
    "imsorry": ("america", "freedom", "sarcasm", "murica"),
    "inigo": ("princess bride", "that word", "misuse", "definition", "wrong word"),
    "interesting": ("dos equis", "most interesting", "i don't always", "beer"),
    "ive": ("apple", "jony ive", "design", "redesign", "you'll love it"),
    "iw": ("wolf", "insanity", "reckless", "production", "yolo"),
    "jd": ("archaic", "old timey", "rap", "translated", "fancy"),
    "jetpack": ("jetpack", "nothing to do", "leaving", "bored", "escape"),
    "jim": ("the office", "jim halpert", "whiteboard", "explain", "point"),
    "joker": ("batman", "joker", "simple", "plan", "villain"),
    "jw": ("jurassic world", "bad idea", "dinosaur", "warning"),
    "keanu": ("conspiracy", "keanu reeves", "what if", "stoned", "theory"),
    "kermit": ("kermit", "tea", "none of my business", "shade", "passive aggressive"),
    "khaby-lame": ("shrug", "obvious", "simple solution", "tiktok"),
    "kk": ("karate", "revenge", "overreaction", "kid"),
    "kombucha": ("kombucha", "unsure", "mixed feelings", "try again", "hmm"),
    "kramer": ("seinfeld", "kramer", "what's going on", "neon"),
    "leo": ("leonardo dicaprio", "strut", "confident", "no idea", "walking"),
    "light": ("lion king", "mufasa", "simba", "kingdom", "forbidden", "borders"),
    "live": ("bill o'reilly", "do it live", "rage", "improvise", "screw it"),
    "ll": ("lizard", "laughing", "hehe", "giggle"),
    "lrv": ("viking", "laundry", "they said", "it will be fun", "chores"),
    "made": ("i made this", "stolen", "credit", "reposted", "plagiarism"),
    "mb": ("south park", "member berries", "nostalgia", "remember"),
    "michael-scott": ("the office", "michael scott", "no god no", "dread", "please no"),
    "midwit": ("bell curve", "iq", "midwit", "smart dumb", "simple"),
    "millers": ("we're the millers", "paid", "underpaid", "salary", "unfair"),
    "mini-keanu": ("keanu", "waiting", "kid", "patient", "mom"),
    "mmm": ("marvin", "minor mistake", "oops", "small error", "guilty"),
    "money": ("futurama", "fry", "take my money", "buy", "want", "shut up"),
    "mordor": ("lord of the rings", "boromir", "one does not simply", "impossible"),
    "morpheus": ("matrix", "what if i told you", "revelation", "truth"),
    "mouth": ("dog", "muzzle", "sales", "engineering", "held back", "silenced"),
    "mw": ("men's wearhouse", "guarantee", "suit", "promise"),
    "nails": ("sand", "nails", "pointless", "futile", "hammer"),
    "nice": ("caddyshack", "bill murray", "which is nice", "consolation", "silver lining"),
    "noah": ("family guy", "what the hell", "confused", "what is this"),
    "noidea": ("dog", "no idea", "clueless", "computer", "faking it"),
    "ntot": ("dog", "fetch", "only throw", "ball", "stubborn"),
    "oag": ("overly attached", "girlfriend", "clingy", "stalker", "creepy"),
    "officespace": ("office space", "lumbergh", "boss", "that'd be great", "passive aggressive"),
    "older": ("star wars", "old", "checks out", "outdated", "still works"),
    "oprah": ("oprah", "you get a", "everybody gets", "giveaway", "generous"),
    "panik-kalm-panik": ("panic", "calm", "relief", "then panic", "three panel", "anxiety"),
    "patrick": ("spongebob", "patrick", "somewhere else", "move it", "not my problem"),
    "perfection": ("star wars", "darth vader", "perfection", "insist", "the real"),
    "persian": ("cat", "shocked", "surprised", "woke up", "yelling"),
    "philosoraptor": ("dinosaur", "raptor", "deep thought", "question", "philosophy"),
    "pigeon": ("anime", "butterfly", "is this a", "misidentify", "wrong"),
    "pooh": ("winnie the pooh", "tuxedo", "fancy", "classy", "same thing", "upgrade"),
    "pool": ("mother", "drowning", "ignored", "favouritism", "neglect", "reddit"),
    "prop3": ("confusing", "extreme", "voting", "ballot"),
    "ptj": ("friends", "phoebe", "joey", "teaching", "repeat after me", "learning"),
    "puffin": ("puffin", "unpopular opinion", "hot take", "controversial"),
    "red": ("red", "fight", "today", "confrontation", "is that what"),
    "regret": ("regret", "bad decision", "jump", "immediately"),
    "remembers": ("pepperidge farm", "remember", "nostalgia", "old days"),
    "reveal": ("scooby doo", "unmask", "villain", "reveal", "it was you"),
    "right": ("star wars", "anakin", "padme", "for the better", "right?", "worried", "four panel"),
    "rollsafe": ("roll safe", "thinking", "smart", "can't if you don't", "big brain", "logic"),
    "sad-biden": ("biden", "sad", "politics", "vote"),
    "sad-boehner": ("boehner", "sad", "politics", "vote"),
    "sad-bush": ("bush", "sad", "politics", "vote"),
    "sad-clinton": ("clinton", "sad", "politics", "vote"),
    "sad-obama": ("obama", "sad", "politics", "vote"),
    "sadfrog": ("pepe", "frog", "feels bad", "sad", "depressed"),
    "saltbae": ("salt bae", "salt", "sprinkle", "flair", "chef"),
    "same": ("the office", "pam", "same picture", "identical", "no difference"),
    "sarcasticbear": ("bear", "sarcasm", "sorry", "know it all"),
    "say": ("simpsons", "bart", "say the line", "catchphrase", "predictable"),
    "sb": ("scumbag brain", "brain", "forgetful", "memory", "self sabotage"),
    "scc": ("sudden clarity", "realisation", "oh no", "clarence", "party"),
    "seagull": ("seagull", "screaming", "somebody once told me", "shrek", "all star", "singing"),
    "sf": ("sealed fate", "doomed", "mom heard", "in trouble", "kid"),
    "sk": ("skeptical", "third world", "kid", "so you're telling me", "doubt"),
    "ski": ("south park", "ski instructor", "bad time", "warning"),
    "slap": ("will smith", "chris rock", "slap", "oscars", "monday", "ruined"),
    "snek": ("snake", "skeptical", "suspicious", "leaf", "wait"),
    "soa": ("seal", "approval", "approve", "good job", "nice"),
    "sohappy": ("happy", "wish", "if only", "dreaming", "hopeful"),
    "sohot": ("zoolander", "mugatu", "so hot right now", "trendy", "popular"),
    "soup-nazi": ("seinfeld", "no soup", "denied", "banned", "refused"),
    "sparta": ("300", "leonidas", "sparta", "kick", "this is"),
    "spiderman": ("spider-man", "pointing", "same", "identical", "blame", "each other"),
    "spirit": ("halloween", "costume", "spirit halloween", "includes", "nothing"),
    "spongebob": ("spongebob", "mocking", "sarcasm", "mimic", "sPoNgEbOb"),
    "ss": ("scumbag steve", "jerk", "freeloader", "bad friend", "hat"),
    "stew": ("carl weathers", "arrested development", "stew", "frugal", "leftovers"),
    "stonks": ("stonks", "stocks", "money", "profit", "investing", "gains"),
    "stop": ("spongebob", "patrick", "scaring him", "misunderstanding", "santa"),
    "stop-it": ("steve harvey", "get some help", "stop it", "intervention"),
    "success": ("success kid", "baby", "fist pump", "win", "victory", "nailed it"),
    "tenguy": ("stoned", "high", "10 guy", "weed", "dumb"),
    "toohigh": ("rent", "too damn high", "expensive", "prices", "cost"),
    "touch": ("simpsons", "skinner", "out of touch", "children are wrong", "denial", "boomer"),
    "tried": ("at least you tried", "participation", "consolation", "effort", "fail"),
    "trump": ("trump", "donald", "best ever", "politics", "bragging"),
    "ugandanknuck": ("knuckles", "de wey", "do you know", "vrchat"),
    "vince": ("vince mcmahon", "wwe", "escalating", "more excited", "reaction", "wrestling"),
    "wallet": ("spongebob", "patrick", "wallet", "logic", "circular", "argument", "dumb"),
    "waygd": ("shrug", "what are ya gonna do", "oh well", "resigned", "whatever"),
    "wddth": ("black panther", "we don't do that here", "wakanda", "forbidden", "not allowed"),
    "whatyear": ("what year is it", "jumanji", "robin williams", "confused", "time"),
    "winter": ("game of thrones", "ned stark", "winter is coming", "brace", "prepare"),
    "wishes": ("genie", "wish", "rules", "can't do that", "impossible request"),
    "wkh": ("hannibal", "eric andre", "who did this", "hypocrite", "shoot", "blame"),
    "woman-cat": ("cat", "yelling", "dinner table", "argument", "confused cat", "smudge"),
    "wonka": ("willy wonka", "condescending", "sarcasm", "tell me more", "patronising"),
    "worst": ("worst day", "so far", "it gets worse", "simpsons", "homer"),
    "xy": ("all the things", "hyperbole", "rage comic", "do all"),
    "yallgot": ("dave chappelle", "tyrone biggums", "crackhead", "any more", "addict"),
    "yodawg": ("xzibit", "yo dawg", "recursion", "i heard you like", "pimp my ride"),
    "yuno": ("y u no", "why", "rage comic", "frustrated"),
    "zero-wing": ("all your base", "zero wing", "engrish", "video game", "retro"),
}
